<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Martin Kolnes, Karin Täht" />


<title>Logistiline regressioon</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<div class="container-fluid main-container">

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Kodu</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Praktikumide materjalid
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="praktikum1.html">1. Praktikum - sissejuhatus</a>
    </li>
    <li>
      <a href="praktikum2.html">2. Praktikum - joonised</a>
    </li>
    <li>
      <a href="praktikum3.html">3. Praktikum - ANOVA</a>
    </li>
    <li>
      <a href="praktikum4v2.html">4. Praktikum - regressioon</a>
    </li>
    <li>
      <a href="praktikum5.html">5. Praktikum - logistiline regressioon</a>
    </li>
    <li>
      <a href="praktikum6.html">6. Praktikum - eksploratiivne faktoranaluus</a>
    </li>
    <li>
      <a href="praktikum7.html">7. Praktikum - Struktuurvorrandite mudelid</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Lisamaterjalid
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lisa_andmente_importimine.html">Andmete importimine</a>
    </li>
    <li>
      <a href="praktikum1_korrelatsioon.html">Korrelatsioon</a>
    </li>
    <li>
      <a href="praktikum1_subsetting.html">Andmete eraldamine</a>
    </li>
    <li>
      <a href="praktikum2_ttestid.html">Keskmiste vordlemine</a>
    </li>
    <li>
      <a href="lisa_joonis.html">Joonis - keskmised</a>
    </li>
  </ul>
</li>
<li>
  <a href="lugemist.html">Soovitused</a>
</li>
<li>
  <a href="about.html">Kontakt</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Logistiline regressioon</h1>
<h4 class="author"><em>Martin Kolnes, Karin Täht</em></h4>

</div>


<p>Laadige alla <a href="https://drive.google.com/open?id=1JlHhXSz-B8wejK43wo231dK--WUv6WgJ">praktikumi andmed</a>.</p>
<div id="kordamine" class="section level1">
<h1>Kordamine</h1>
<ol style="list-style-type: decimal">
<li><p>Tehke PISA andmestiku alusel regressioonanalüüs, kus sõltuvaks tunnuseks on matemaatika testi tulemus (PVMATH) ja prediktoriteks enese-tõhusus teaduses (SCIEEFF; <em>science self-efficacy</em>) ja mina-pilt loodusteadustes (SCSCIE; <em>science self-concept</em>).</p></li>
<li><p>Arvutage ka standardiseeritud regressioonikordajad ja mudeli parameetrite usalduspiirid.</p></li>
<li><p>Kas mudeli jäägid jaotuvad normaalajaotusel vastavalt?</p></li>
</ol>
</div>
<div id="logistiline-regressioon" class="section level1">
<h1>Logistiline regressioon</h1>
<p>Kui lineaarse regressiooni puhul oli sõltuv tunnus numbriline, siis logistilise regressiooni puhul on sõltuv tunnus kategoriaalne. Logistiline mudel ennustab prediktorite väärtuste abil võimalust kuuluda mingisse kategooriasse. Binaarne logistiline regressioon on selline, mille puhul on sõltuval tunnusel ainult 2 taset (nt kas inimesel esineb konkreetne haigus või mitte). Multinomiaalse logistilise regressiooni puhul on sõltuva muutuja tasemeid rohkem kui 2.</p>
</div>
<div id="binaarne-logistiline-regressioon---uhe-prediktoriga-mudel" class="section level1">
<h1>Binaarne logistiline regressioon - ühe prediktoriga mudel</h1>
<p>Andmetabel nimega “cowles” käsitleb seost tudengite isiksuseomaduste ja psühholoogilistes uurimustes osalemise valmiduse vahel. Andmestik koosneb neljast muutujast:</p>
<ul>
<li><em>neuroticism</em> - Eysencki isiksuseküsimustku neurootilisuse alaskaala skoor;</li>
<li><em>extraversion</em> - ekstravertsuse alaskaala skoor;</li>
<li><em>sex</em> - sugu (<em>female</em>, <em>male</em>);</li>
<li><em>volunteer</em> - kas tudeng on valmis osalema edasises uurimistöös (<em>no</em>, <em>yes</em>);</li>
</ul>
<p>Esmase ülevaate saamiseks andmetest kasutage funktsiooni <em>summary</em>.</p>
<pre class="r"><code>summary(cowles)</code></pre>
<pre><code>##   neuroticism     extraversion       sex      volunteer
##  Min.   : 0.00   Min.   : 2.00   female:780   no :824  
##  1st Qu.: 8.00   1st Qu.:10.00   male  :641   yes:597  
##  Median :11.00   Median :13.00                         
##  Mean   :11.47   Mean   :12.37                         
##  3rd Qu.:15.00   3rd Qu.:15.00                         
##  Max.   :24.00   Max.   :23.00</code></pre>
<p>Teeme kõigepealt logistilise regressioonmudeli, milles sõltuvaks tunnuseks on valmidus osaleda uurimistöös (tunnus <em>volunteer</em>) ja ennustame seda ekstravertsuse skoori kaudu. Logistilise mudeli tegemiseks kasutame funktsiooni <em>glm</em> (<em>generalized linear model</em>). Selle funktsiooni kasutamine on sarnane eelmises praktikumis kasutatud <em>lm</em> funktsiooniga. Kõigepealt peame sisestama mudelisse kaasatavate muutujate nimed (“sõltuv tunnus ~ sõltumatu tunnus”) ning seejärel andmestiku nime (“data = andmestik”). Funktsiooni <em>glm</em> puhul lisandub argument <em>family</em>, mille abil määrame, millist tüüpi mudelit teha tahame. Logistilise mudeli puhul paneme argumendi <em>family</em> väärtuseks <em>binomial()</em>. (Kui meil juhtub esinema puuduvaid andmeid, saame need välja jätta lisades argumendi <em>na.action=na.omit</em>. Samuti saaksime argumendi <em>subset</em> abil määrata valimit kitsendava tingimuse.)</p>
<pre class="r"><code>cowles.mudel1 &lt;- glm(volunteer ~ extraversion, data=cowles, family=binomial())</code></pre>
<p>Uurime mudeli väljundit.</p>
<pre class="r"><code>summary(cowles.mudel1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = volunteer ~ extraversion, family = binomial(), 
##     data = cowles)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3379  -1.0584  -0.9299   1.2725   1.6243  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.13942    0.18538  -6.146 7.93e-10 ***
## extraversion  0.06561    0.01414   4.640 3.49e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1933.5  on 1420  degrees of freedom
## Residual deviance: 1911.5  on 1419  degrees of freedom
## AIC: 1915.5
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Vaatame väljundi alaosa nimega <strong>Coefficients</strong>. Tulbas <strong>Estimate</strong> on ära toodud mudeli parameetrite - vabaliikme (<em>Intercept</em>) ja regressioonikordaja - väärtused. Tulbas <strong>Std. Error</strong> on ära toodud standardviga (kui suurt kordaja kõikumist võib oodata erinevates valimites). Tulbas <strong>z value</strong> on toodud z-statistiku väärtus, mis on tuntud ka <em>Waldi</em> statistiku nime all. See on saadud jagades regressioonikordaja väärtuse ja standardvea omaga. <strong>Tulbas Pr(&gt;|z|)</strong> on märgitud z-statistiku kaudu arvutatud p-väärtus, mille abil saame hinnata, kas prediktor omab olulist seost sõltuva muutujaga. Praegusel juhul on ekstravertsuse regressioonikordajale vastav p-väärtus <span class="math inline">\(3.49e-06\)</span> ehk <span class="math inline">\(3.49 * 10^{-6}\)</span>. Antud prediktori olulisusele nivool p &lt; .001 viitavad ka rea lõpus olevad 3 tärni.</p>
<div id="riskisuhte-arvutamine" class="section level2">
<h2>Riskisuhte arvutamine</h2>
<p>Logistilise regressiooni puhul on regressioonikordajad logaritmskaalal ja sellisel kujul on nende tõlgendamine üsna keeruline. Olukord läheb paremaks, kui teisendame regressioonikordaja eksponent-funktsiooni abil (logaritmimise pöördfunktsioon). Selle tulemusel saadud arve nimetatakse <strong>riskisuheteks</strong> või ka <strong>šansside suheteks</strong>. Riskisuhete saamiseks kasutame funktsioone <em>coef</em> ja <em>exp</em>. Funktsioonile <em>coef</em> anname argumendiks mudeli nime. See funktsioon eraldab mudelist ainult mudeli parameetrite väärtused. Funktsioonile <em>exp</em> anname argumendiks funktsioonist <em>coef</em> saadud väärtused. R-is saame teha seda hierahriliselt:</p>
<pre class="r"><code>exp(coef(cowles.mudel1))</code></pre>
<pre><code>##  (Intercept) extraversion 
##     0.320005     1.067813</code></pre>
<p><strong>Kuidas riskisuhteid tõlgendada?</strong> 1-st suurem riskisuhte väärtus näitab, et prediktori väärtuse suurenedes ühe ühiku võrra suurenevad sündmuse esinemise šansid nii mitu korda kui on riskisuhte väärtus. 1-st väiksem riskisuhte väärtus näitab, et prediktori väärtuse suurendes ühe ühiku võrra sündmuse esinemise šansid vähenevad 1/riskisuhe korda. Antud juhul on ekstravertsuse riskisuhte väärtuseks ümmardatuna 1.068. See tähendab, et kui ekstravertsuse skoor suureneb ühe punkti võrra suureneb jaatava vastuse tõenäosus 1.068 korda ehk 6.8% võrra.<br />
Kuidas me teame, et need on just jaatava (ja mitte eitava) vastuse šansid? Vaikimisi käivad numbrid selle sõltuva muutuja taseme kohta, mille nimetus paikneb tähestikulises järjekorras tagapool (eespool paiknev kategooria on valitud taustkategooriaks). Antud juhul oli meie sõltuval muutujal “volunteer” 2 taset: <em>no</em> ja <em>yes</em>. Kuna <em>yes</em> algustäht paikneb tähestikus tagapool on praegusel juhul just see, mille šansse numbrid näitavad.</p>
</div>
<div id="riskisuhte-usaldusvahemikud" class="section level2">
<h2>Riskisuhte usaldusvahemikud</h2>
<p>Lineaarse regressiooni puhul nägime, et üheks täiendavaks võimaluseks hinnata prediktorite mõju usaldusväärsust olid regressioonikordajate 95% -usaldusvahemikud. Sedasama lähenemist saame kasutada ka logistilise regressiooni puhul, arvutades usaldusvahemikud riskisuhete jaoks. Usaldusvahemikud saime funktsiooni <em>confint</em> abil. Logistilise regressiooni puhul lisame veel funktsiooni <em>exp</em> (logaritmimise pöördfunktsioon).</p>
<pre class="r"><code>exp(confint(cowles.mudel1))</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                  2.5 %    97.5 %
## (Intercept)  0.2217862 0.4589052
## extraversion 1.0387831 1.0980308</code></pre>
<p>Riskisuhte usaldusintervallide puhul on oluline vaadata, kas väärtus 1 jääb usaldusintervalli sisse. Kui nii juhtub, viitab see sellele, et prediktori mõju pole usaldusväärne: mõnedes valimites oleks mõju suund ühesugune ja teistes valimites teistsugune. Antud juhul on ekstravertsuse mõlemad usalduspiirid ühest suuremad. Seega võime olla üsna kindlad, et ekstravertsus mõjutab uurimustes osalemise valmidust positiivselt.</p>
</div>
<div id="hii-ruut-test" class="section level2">
<h2>Hii-ruut test</h2>
<p>Regressioonikordajad, riskisuhted ja nende usaldusvahemikud iseloomustavad eraldiseisvaid prediktoreid. Lisaks sellele on mudeli väljundis toodud ka mudeli sobitusastme näitajad. Mudeli jääkhälbimus (<em>Residual deviance</em>) iseloomustab meie koostatud mudeli logaritmilise tõepärafunktsiooni väärtust. Viimane põhineb mudeli järgi ennustatud ja tegelike väärtustega seotud tõenäosuste summeerimisel. Mida parem mudel, seda väiksem väärtus. Väljundis toodud <strong>Null Deviance</strong> on sama näitaja ainult vabaliiget sisaldava mudeli jaoks, milles muutujate vaheline seos puudub (nn nullmudel). Kui <strong>Residual deviance</strong> on väiksem kui <strong>Null deviance</strong>, tähendab see, et koostatud mudel on parem kui nullmudel. Selle üle, kas erinevus nullmudelist on piisavalt suur, saab otsustada <span class="math inline">\({\chi}^2 -\)</span>testi (hii-ruuttesti) abil. Mingil põhjusel funktsioon <em>glm</em> seda välja ei arvuta ja meil tuleb seda ise teha funktsiooni <em>anova</em> abil. Defneerime kõigepealt ilma prediktoriteta ainult vabaliiget sisaldava nullmudeli.<br />
Selle valem on kujul: “sõltuv muutuja ~ 1”.</p>
<pre class="r"><code>cowles.nullmudel &lt;- glm(volunteer ~ 1, data=cowles, family=binomial())</code></pre>
<p>Nüüd võrdleme nullmudelit ja eelnevalt koostatud mudelit anname <em>anova</em> funktsiooniga. Argumendi <em>test=“Chisq”</em> abil anname teada, et tahame kasutada hii-ruut testi.</p>
<pre class="r"><code>anova(cowles.nullmudel, cowles.mudel1, test=&quot;Chisq&quot;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: volunteer ~ 1
## Model 2: volunteer ~ extraversion
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1      1420     1933.5                          
## 2      1419     1911.5  1   22.022 2.695e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Vaatame tabeli teise rea kahte viimast tulpa, milles on toodud hii-ruut statistik (<em>Deviance</em>), ja selle p-väärtus. Antud p-väärtuse põhjal võime öelda, et mudeli sobitusaste oli nullmudeli omast oluliselt parem (<span class="math inline">\({\chi}^2\)</span> = 22.02, p &lt; .001).</p>
</div>
<div id="pseudo-determinatsioonikordaja" class="section level2">
<h2>Pseudo-determinatsioonikordaja</h2>
<p>Lineaarse regressiooni puhul saime välja arvutada mudeli determinatsioonikordaja(<span class="math inline">\(R^2\)</span>), mis näitas kui suure osa sõltuva tunnuse hajuvusest mudel ära kirjeldas. Logistilise regressiooni puhul saame arvutada näitajaid, mida nimetatakse pseudo-determinatsioonikordajaks. Need varieeruvad samuti 0-st 1-ni ja näitavad mudeli sobitustusastme headust (mida suurem väärtus seda parem). Sõltuvalt arvutuskäigust on pseudo-determinatsioonikordajaid mitut tüüpi. Arvutame praegusel juhul ühe sagedamini kasutatava, mida nimetatakse Nagelkerke <span class="math inline">\(R^2\)</span>. Selle jaoks peame kõigepealt installima lisamooduli <em>fmsb</em>.</p>
<pre class="r"><code>install.packages(&quot;fmsb&quot;)</code></pre>
<p>Seejärel saame lisamooduli laadida ja kasutada selles olevat funktsiooni <em>NagelkerkeR2</em>:</p>
<pre class="r"><code>library(fmsb)
NagelkerkeR2(cowles.mudel1)</code></pre>
<pre><code>## $N
## [1] 1421
## 
## $R2
## [1] 0.02068324</code></pre>
<p><strong>Pseudo-determinatsioonikordaja</strong> väärtused ongi tüüpiliselt üsna madalad. Kordajat kasutatakse tüüpiliselt selleks, et hinnata, kas prediktorite lisamine tegi mudelit paremaks.</p>
</div>
<div id="standardiseeritud-skooride-kasutamine" class="section level2">
<h2>Standardiseeritud skooride kasutamine</h2>
<p>Eelnevalt kasutasime mudelis ekstravertsuse toorskoore, mis teeb tulemuste tõlgendamise keeruliseks. See tähendab, et me ei oska eriti täpselt hinnata, kas ühe-punktiline muutus ekstravertsuse skooris on suur või väike. Seetõttu on vahepeal mõistlik numbriline prediktor kaasata standardiseerituna ehk standarhälbe ühikutesse teisendatuna. Sel juhul saame riskisuhteid tõlgendades öelda, et prediktori muutudes ühe standardhälbe võrra muutuvad huvipakkuva sündmuse esinemise šanssid nii mitu korda.<br />
Prediktori saame standardiseerida funktsiooniga <em>scale()</em>:</p>
<pre class="r"><code>cowles.mudel1 &lt;- glm(volunteer ~ scale(extraversion), data=cowles, family=binomial())
exp(coef(cowles.mudel1))</code></pre>
<pre><code>##         (Intercept) scale(extraversion) 
##           0.7206583           1.2910767</code></pre>
<p>Võime järeldada, et ekstravertsuse suurenedes ühe standardhälbe võrra suureneb uurimustes osalemise valmidus 1.29 korda ehk 29% võrra.</p>
</div>
</div>
<div id="binaarne-logistiline-regressioon---kahe-prediktoriga-mudel" class="section level1">
<h1>Binaarne logistiline regressioon - kahe prediktoriga mudel</h1>
<p>Mudelitesse saab prediktorina kaasata ka kategoriaalseid muutujaid. Teeme uue mudeli, lisades täiendava pretiktorina vastaja soo (tunnus <em>sex</em>) ja uurime mudeli väljundit.</p>
<pre class="r"><code>cowles.mudel2 &lt;- glm(volunteer ~ scale(extraversion) + sex, data=cowles, family=binomial())
summary(cowles.mudel2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = volunteer ~ scale(extraversion) + sex, family = binomial(), 
##     data = cowles)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3860  -1.0499  -0.9035   1.2533   1.6853  
## 
## Coefficients:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         -0.21765    0.07259  -2.998  0.00271 ** 
## scale(extraversion)  0.25494    0.05519   4.619 3.85e-06 ***
## sexmale             -0.24662    0.10929  -2.256  0.02404 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1933.5  on 1420  degrees of freedom
## Residual deviance: 1906.4  on 1418  degrees of freedom
## AIC: 1912.4
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Tabelist <strong>Coefficients</strong> näeme p-väärtuste abil, et mõlemad prediktorid on olulised. Kategoriaalsete muutujate puhul valitakse üks kategooriatest baaskategooriaks, millega ülejäänud kategooriaid võrreldakse. Praegusel juhul on muutujal <em>sex</em> kaks taset (<em>female</em> ja <em>male</em>). Vaikimisi on baaskategooriaks valitud <em>female</em>, tulenevalt sellest, et <em>female</em> on tähestukuliselt eespool võrreldes <em>male</em>’iga. Seega näitab vastav regressioonikordaja, kui erinev on kategooria <em>male</em> võrreldes kategooriaga <em>female</em>. Miinusmärgist selle kordaja ees võime järeldada, et meeste puhul on jaatava vastuse tõenäosus naistega võrreldes madalam. Kordajate arusaadavamaks tõlgendamiseks arvutame neist jällegi riskisuhted.</p>
<pre class="r"><code>exp(coef(cowles.mudel2))</code></pre>
<pre><code>##         (Intercept) scale(extraversion)             sexmale 
##           0.8044055           1.2903863           0.7814391</code></pre>
<p>Ekstravertsuse riskisuhe on jäänud samaks. Vastaja soo riskisuhtest võime järeldada, et meeste puhul on jaatava vastamise tõenäosus 78% naiste jaatava vastuse tõenäosusest. Ehk naiste puhul jaatava vastuse tõenäosus <span class="math inline">\(1/0.78 = 1.28\)</span> korda suurem kui meeste puhul.</p>
<p>Hindame prediktoreid ka 95%-usaldusvahemike abil.</p>
<pre class="r"><code>exp(confint(cowles.mudel2))</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                         2.5 %    97.5 %
## (Intercept)         0.6974271 0.9271049
## scale(extraversion) 1.1587831 1.4388556
## sexmale             0.6304839 0.9678052</code></pre>
<p>Nagu näha ei sisalda kummagi prediktori vahemikud väärtust 1 ja sellest tulenevalt võib neid lugeda usaldusväärseteks.</p>
<p>Arvutame mudeli pseudo-determinatsioonikordaja.</p>
<pre class="r"><code>NagelkerkeR2(cowles.mudel2)</code></pre>
<pre><code>## $N
## [1] 1421
## 
## $R2
## [1] 0.02543564</code></pre>
<p>See on jäänud enam-vähem samaks, nii et soo lisamine mudeli kirjeldusvõimet väga palju paremaks ei teinud.</p>
</div>
<div id="multinomiaalne-logistiline-regressioon" class="section level1">
<h1>Multinomiaalne logistiline regressioon</h1>
<p>Vaatame põgusalt ka logistilist regressiooni sõltuva muutuja korral, millel on rohkem kui kaks taset. Kasutame selleks paketi <em>nnet</em> funktsiooni <em>multinom()</em>.</p>
<pre class="r"><code>install.packages(&quot;nnet&quot;) # installeerime paketi</code></pre>
<pre class="r"><code>library(nnet) </code></pre>
<p>Andmetabelis ESS on 4 muutujat 2008. aasta Euroopa Sotsiaaluuringu Eesti vastajaid puudutavatest andmetest. üks tunnustest puudutab seda, millise erakonna poolt hääletas vastaja viimastel valimistel (tunnus <em>partei</em>). Näitlikustamise lihtsuse huvides olen antud tabelisse alles jätnud ainult 3 valimis kõige suuremat toetust omavat parteid (IRL, Kesk ja Reform). Teeme mudeli, milles ennustame erakondlikku eelistust vastaja vanuse kaudu. Vaikimisi võetakse baaskategooriaks tähestiku järjekorras kõige esimene kategooria, antud juhul oleks selleks IRL. (Baaskategooria saab muuta funktsiooni <em>relevel</em> abil.)</p>
<pre class="r"><code>ess.mudel1 &lt;- multinom(partei ~ vanus, data = ESS)</code></pre>
<pre><code>## # weights:  9 (4 variable)
## initial  value 727.281335 
## final  value 677.750378 
## converged</code></pre>
<p>Uurime tulemusi:</p>
<pre class="r"><code>summary(ess.mudel1)</code></pre>
<pre><code>## Call:
## multinom(formula = partei ~ vanus, data = ESS)
## 
## Coefficients:
##        (Intercept)        vanus
## Kesk    -0.6269266  0.023066461
## Reform   1.1064595 -0.006418908
## 
## Std. Errors:
##        (Intercept)       vanus
## Kesk     0.3475546 0.006384485
## Reform   0.3145498 0.006113478
## 
## Residual Deviance: 1355.501 
## AIC: 1363.501</code></pre>
<p>Väljund on jaotatud kaheks osaks: regressioonikordajad ja standardvead. Regressioonikordajad on toodud kummagi partei jaoks eraldi. Nende põhjal on näha, et võrreldes IRL-iga suurendab kasvav vanus Keskerakonna poolt hääletamise tõenäosust, samas kui Reformierakonna toetamise tõenäosusega ei tundu seost olevat. Kahjuks ei anna multinom funktsioon meile p-väärtusi. Nende välja arvutamiseks on erinevaid viise, aga kõige lihtsam on kasutada paketi <em>stargazer</em> samanimelist funktsiooni, mis annab meile regressioonimudeli tulemused ja lisab sinna p-väärtused.</p>
<pre class="r"><code>install.packages(&quot;stargazer&quot;)</code></pre>
<pre class="r"><code>library(stargazer)
stargazer(ess.mudel1, type=&quot;text&quot;, out=&quot;multi1.htm&quot;)</code></pre>
<pre><code>## 
## ==============================================
##                       Dependent variable:     
##                   ----------------------------
##                        Kesk         Reform    
##                        (1)            (2)     
## ----------------------------------------------
## vanus                0.023***       -0.006    
##                      (0.006)        (0.006)   
##                                               
## Constant             -0.627*       1.106***   
##                      (0.348)        (0.315)   
##                                               
## ----------------------------------------------
## Akaike Inf. Crit.   1,363.501      1,363.501  
## ==============================================
## Note:              *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>Vanuse mõju suurust saab hinnata riskisuhete abil:</p>
<pre class="r"><code>exp(coef(ess.mudel1))</code></pre>
<pre><code>##        (Intercept)     vanus
## Kesk     0.5342312 1.0233345
## Reform   3.0236343 0.9936016</code></pre>
<p>Keskerakonna regressioonikordaja riskisuhte alusel võime järeldada, et lisanduv eluaasta suurendab Keskerakonna toetamise suhtelist tõenäosust võrreldes IRL-i toetamise tõenäosusega 1.02 korda ehk 2%.</p>
</div>
<div id="ulesanded" class="section level1">
<h1>Ülesanded</h1>
<ol style="list-style-type: decimal">
<li>Andmetabelist nimega neeme on Marko Neeme magistritöö (Neeme, 2012) andmed, milles uuriti 50-70-aastaste meeste suhtumist eesnäärmevähi skriiningtesti. Tunnus “”valmidus“, näitab testis osalemise valmidust (tasemed pigem jah, ja pigem ei). Lisaks on tabelis ära toodud Suure Viisiku isiksuseomadused: neurootilisus (tunnus N), ekstravertsus (E), avatus kogemusele (O), sotsiaalsus (A) ja meelekindlus (C). Koostage binaarse logistilise regressiooni mudel, mis ennustab skriiningtestis osalemise valmidust Suure Viisiku isiksuseomaduste kaudu.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Esialgu tuleks saada ülevaade andmetest. Kasutage funktsiooni <em>summary</em>. Milline on oslejate keskmine vanus? Missugune on “valmiduse” jaotus?</p></li>
<li><p>Tehke ekstravertsuse tulemustest histogramm.</p></li>
<li><p>Millised isiksusomadused omavad olulist seost valmidusega? Kas need omadused suurendavad või vähendavad testis osalemise valmidust?</p></li>
<li><p>Arvutage välja riskisuhted ja nende 95%-usaldusvahemikud? Milline omadus mõjutab osalemisvalmidust kõige tugevamini?</p></li>
<li><p>Arvutage mudeli sobitusastet näitav hii-ruut-statistik ja selle p-väärtus.</p></li>
<li><p>Leidke mudeli pseudo-determinatsioonikordja.</p></li>
</ol>
</div>
<div id="lisad" class="section level1">
<h1>LISAD</h1>
<div id="tingimuslik-tihedusfunktsiooni-joonis-conditional-density-plot" class="section level2">
<h2>Tingimuslik tihedusfunktsiooni joonis (conditional density plot)</h2>
<p>Kui meil on ühe numbrilise prediktoriga logistiline mudel (nagu praegu), siis saab vastavat seost kujutada tingimusliku tihedusfunktsiooni joonise abil. Selle saame funktsiooni <em>cdplot</em> kaudu.</p>
<pre class="r"><code>cdplot(volunteer ~ extraversion, data=cowles)</code></pre>
<p><img src="praktikum5_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Joonisel on näha, milline on jaatavate ja eitavate vastuste osakaal valimis erinevate ekstravertsuse tasemete puhul. Heledam hall toon tähistab jaatava vastuse tõenäosust ja tumedam eitava vastuse oma.</p>
</div>
<div id="vastuse-tonaosus-prediktori-konkreetse-vaartuse-korral" class="section level2">
<h2>Vastuse tõnäosus prediktori konkreetse väärtuse korral</h2>
<p>Mudeli parameetrite abil saame välja arvutada ka, milline on jaatava vastuse tõenäosus mingil ekstravertsuse tasemel. Logistilise regressioonimudeli parameetrid on logaritmiliselt teisendatud ansside kujul ehk keerulisemalt öeldes, vastavad tõenäosused on teisendatud logit-funktsiooni abil. Defineerime kõigepealt logit-funktsiooni pöördfunktsiooni expit, mille abil saame logaritmilised anssid tagasi tõenäosusteks.</p>
<pre class="r"><code>expit &lt;- function(x) exp(x) / (1+exp(x))</code></pre>
<p>Seejärel küsime funktsiooni <em>coef</em> abil oma mudelist parameetrite väärtused.</p>
<pre class="r"><code>coef(cowles.mudel1)</code></pre>
<pre><code>##         (Intercept) scale(extraversion) 
##          -0.3275901           0.2554766</code></pre>
<p>Nüüd saame parameetrite väärtused anda funktsioonile <em>expit</em>. Seda tuleks teha sellisel kujul: kõigepealt vabaliikme väärtus, millele liidame otsa prediktori regressioonikordaja väärtuse korrutatuna meid huvitava prediktori taseme väärtusega. Kui sooviksime arvutada, milline on jaatava vastuse tõenäosus, kui ekstravertsuse skoor on 2 standardhälvet üle keskmise, näeks see välja nii.</p>
<pre class="r"><code>expit(-0.3275901 + 2*0.2554766)</code></pre>
<pre><code>## [1] 0.5457128</code></pre>
<p>Nagu näha, ennustab meie mudel sellisel juhul jaatava vastuse tõenäosuseks umbes 55%.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
